#ifndef CONFIG_H
#define CONFIG_H

#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64

#define GAME_TARGET_FPS 30
#define PLAYER_START_X 12
#define PLAYER_START_Y 32
#define PLAYER_LIVES 3
#define PLAYER_SPEED 1
#define PLAYER_WIDTH 5
#define PLAYER_HEIGHT 3

#define MAX_BULLETS 8
#define MAX_ENEMIES 8
#define BULLET_SPEED 2
#define ENEMY_SPEED 1
#define ENEMY_WIDTH 3
#define ENEMY_HEIGHT 3
#define ENEMY_SCORE_VALUE 10
#define WIN_SCORE 100

#define JOYSTICK_CENTER 2048
#define JOYSTICK_DEADZONE 350
#define JOYSTICK_X_ADC_CHANNEL 0
#define JOYSTICK_Y_ADC_CHANNEL 3

#endif
