#ifndef CONFIG_H
#define CONFIG_H

#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64

#define INPUT_MODE_BUTTONS 0
#define INPUT_MODE_ADC_JOYSTICK 1
#define INPUT_MODE INPUT_MODE_BUTTONS

#if (INPUT_MODE != INPUT_MODE_BUTTONS) && (INPUT_MODE != INPUT_MODE_ADC_JOYSTICK)
#error "Unsupported INPUT_MODE"
#endif

#define GAME_TARGET_FPS 30
#define PLAYER_START_X 12
#define PLAYER_START_Y 32
#define PLAYER_LIVES 3
#define PLAYER_SPEED 1
#define PLAYER_WIDTH 5
#define PLAYER_HEIGHT 3
#define PLAYER_SHOT_COOLDOWN_MS 150

#define MAX_BULLETS 128
#define MAX_ENEMIES 8
#define BULLET_SPEED 2
#define ENEMY_SPEED 1
#define ENEMY_WIDTH 3
#define ENEMY_HEIGHT 3
#define ENEMY_SCORE_VALUE 10
#define WIN_SCORE 100
#define SOUND_DAC_CENTER 2048U
#define SOUND_DAC_AMPLITUDE 100U
#define SOUND_DAC_MIN 1U
#define SOUND_DAC_MAX 4095U

#define APP_MODE_GAME 0
#define APP_MODE_SOUND_TEST 1
#define APP_MODE APP_MODE_SOUND_TEST

#if (APP_MODE != APP_MODE_GAME) && (APP_MODE != APP_MODE_SOUND_TEST)
#error "Unsupported APP_MODE"
#endif

#define JOYSTICK_ADC_X_CHANNEL ADC_CH_ADC0
#define JOYSTICK_ADC_Y_CHANNEL ADC_CH_ADC1
#define JOYSTICK_ADC_X_PIN PORT_Pin_0
#define JOYSTICK_ADC_Y_PIN PORT_Pin_1
#define JOYSTICK_ADC_PORT MDR_PORTD
#define JOYSTICK_ADC_PORT_CLOCK RST_CLK_PCLK_PORTD
#define JOYSTICK_ADC_CENTER 2048
#define JOYSTICK_ADC_DEADZONE 450
#define JOYSTICK_ADC_TIMEOUT 50000U

#endif
